# PUERTO
# Usar el puerto asignado por Railway o 8000 por defecto
server.port=${PORT:8000}

spring.application.name=aurora-admin

# BASE DE DATOS (PostgreSQL)
# Railway inyecta la URL completa en la variable DATABASE_URL.
# El driver es lo suficientemente inteligente para extraer user/pass de ahí.
spring.datasource.url=${DATABASE_URL}
# Forzamos el driver correcto
spring.datasource.driver-class-name=org.postgresql.Driver

# INTEGRIDAD CON DJANGO
# Le decimos a Hibernate: "NO TOQUES LA ESTRUCTURA".
# Django es el dueño de las tablas. Hibernate solo debe validar que existan.
spring.jpa.hibernate.ddl-auto=validate

# Mostrar SQL en logs (útil para debug, desactivar en prod real si hay mucho tráfico)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Dialecto específico para aprovechar funciones de Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# REDIS (Tiempo Real)
# Railway inyecta la URL completa en REDIS_URL
# Spring Boot Data Redis sabe leer esta URL directamente.
spring.data.redis.url=${REDIS_URL}

# Timeouts para evitar bloqueos si la red falla
spring.data.redis.timeout=2000
spring.data.redis.connect-timeout=2000

# SEGURIDAD (Spring Security)

#login por defecto de Spring Security para probar rápido:
spring.security.user.name=admin
spring.security.user.password=${ADMIN_PASSWORD:admin123}


# VARIOS
# Formato de fechas en JSON (ISO-8601)
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
spring.jackson.time-zone=UTC

# Thymeleaf (para las vistas HTML)
spring.thymeleaf.cache=false # Desactivar caché para ver cambios rápido en desarrollo
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8